/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjpessoatp4;

/**
 *
 * @author unisanta
 */
public class PessoaIHM extends javax.swing.JFrame {

    /**
     * Creates new form PessoaIHM
     */
    public PessoaIHM() {
        initComponents();
        jBtnDeletar.setEnabled(false);
        jBtnAtualizar.setEnabled(false);
    }
    private void limpar()
    {
        jTxtCodigo.setText("");
        jTxtNome.setText("");
        jTxtSexo.setText("");
        jTxtIdade.setText("");          
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jTxtCodigo = new javax.swing.JTextField();
        jTxtSexo = new javax.swing.JTextField();
        jTxtIdade = new javax.swing.JTextField();
        jBtnSalvar = new javax.swing.JButton();
        jBtnConsultar = new javax.swing.JButton();
        jBtnAtualizar = new javax.swing.JButton();
        jBtnDeletar = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel.setText("Código");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Sexo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Idade");
        jLabel3.setToolTipText("");

        jTxtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });

        jTxtCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTxtSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSexoActionPerformed(evt);
            }
        });

        jTxtIdade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdadeActionPerformed(evt);
            }
        });

        jBtnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnSalvar.setText("Salvar");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        jBtnConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnAtualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnAtualizar.setText("Atualizar");
        jBtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtualizarActionPerformed(evt);
            }
        });

        jBtnDeletar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnDeletar.setText("Deletar");
        jBtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeletarActionPerformed(evt);
            }
        });

        jBtnLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnLimpar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSalvar)
                    .addComponent(jBtnConsultar)
                    .addComponent(jBtnAtualizar)
                    .addComponent(jBtnDeletar)
                    .addComponent(jBtnLimpar))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void jTxtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSexoActionPerformed

    private void jTxtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdadeActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        // TODO add your handling code here:
         umaPessoa.setCodigo(jTxtCodigo.getText());
        umaPessoa.setNome(jTxtNome.getText());
        umaPessoa.setSexo(jTxtSexo.getText());
        umaPessoa.setIdade(jTxtIdade.getText());
        PessoaBLL.validaDados('i',umaPessoa);
        if (Erro.getErro())
            javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        else
            javax.swing.JOptionPane.showMessageDialog(null,"Dados inseridos com sucesso!");
       
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jBtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeletarActionPerformed
        // TODO add your handling code here:
        umaPessoa.setCodigo(jTxtCodigo.getText());
        umaPessoa.setNome(null);
        umaPessoa.setSexo(null);
        umaPessoa.setIdade(null);
        PessoaBLL.validaCodigo('d',umaPessoa);
        if (Erro.getErro())
            javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        else
            {
            limpar();    
            javax.swing.JOptionPane.showMessageDialog(null,"Dados apagados com sucesso!");
            limpar();
            jBtnDeletar.setEnabled(false);
         jBtnAtualizar.setEnabled(false);
            }   
    }//GEN-LAST:event_jBtnDeletarActionPerformed

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        // TODO add your handling code here:
         umaPessoa.setCodigo(jTxtCodigo.getText());
        umaPessoa.setNome(null);
        umaPessoa.setSexo(null);
        umaPessoa.setIdade(null);
        PessoaBLL.validaCodigo('c',umaPessoa);
        if (Erro.getErro())
            javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        else
            {
            jTxtCodigo.setText(umaPessoa.getCodigo());
            jTxtNome.setText(umaPessoa.getNome());
            jTxtSexo.setText(umaPessoa.getSexo());
            jTxtIdade.setText(umaPessoa.getIdade());
            jBtnDeletar.setEnabled(true);
            jBtnAtualizar.setEnabled(true);
            }
    }//GEN-LAST:event_jBtnConsultarActionPerformed

    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
        // TODO add your handling code here:
        limpar();
         jBtnDeletar.setEnabled(false);
         jBtnAtualizar.setEnabled(false);
    }//GEN-LAST:event_jBtnLimparActionPerformed

    private void jBtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtualizarActionPerformed
        // TODO add your handling code here:
         umaPessoa.setCodigo(jTxtCodigo.getText());
        umaPessoa.setNome(jTxtNome.getText());
        umaPessoa.setSexo(jTxtSexo.getText());
        umaPessoa.setIdade(jTxtIdade.getText());
        PessoaBLL.validaDados('a',umaPessoa);
        if (Erro.getErro())
            javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        else
            javax.swing.JOptionPane.showMessageDialog(null,"Dados alterados com sucesso!");  
        jBtnDeletar.setEnabled(false);
         jBtnAtualizar.setEnabled(false);
    }//GEN-LAST:event_jBtnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaIHM().setVisible(true);
            }
        });
    }
    private Pessoa umaPessoa = new Pessoa();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAtualizar;
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnDeletar;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtIdade;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtSexo;
    // End of variables declaration//GEN-END:variables
}
