/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame05;
import javax.swing.JOptionPane;
/**
 *
 * @author unisanta
 */
public class DisciplinaIHM extends javax.swing.JFrame {

    /**
     * Creates new form DisciplinaIHM
     */
    public DisciplinaIHM() {
        initComponents();
        jBtnDeletar.setEnabled(false);
        jBtnAtualizar.setEnabled(false);
        
    }
    public void limpar(){
        jTxtCodigo.setText("");
        jTxtNome.setText("");
        jTxtCargaHoraria.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jTxtCargaHoraria = new javax.swing.JTextField();
        JbtnSalvar = new javax.swing.JButton();
        jBtnConsultar = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jBtnDeletar = new javax.swing.JButton();
        jBtnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome da disciplina");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Carga Horária");

        JbtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JbtnSalvar.setText("Salvar");
        JbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSalvarActionPerformed(evt);
            }
        });

        jBtnConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        jBtnDeletar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnDeletar.setText("Deletar");
        jBtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeletarActionPerformed(evt);
            }
        });

        jBtnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnAtualizar.setText("Atualizar");
        jBtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JbtnSalvar)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jBtnConsultar))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(jTxtCargaHoraria)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtnLimpar)
                                    .addGap(31, 31, 31)
                                    .addComponent(jBtnDeletar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jBtnAtualizar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnSalvar)
                    .addComponent(jBtnConsultar)
                    .addComponent(jBtnLimpar)
                    .addComponent(jBtnDeletar))
                .addGap(18, 18, 18)
                .addComponent(jBtnAtualizar)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //EVENTO BOTÃO SALVAR
    private void JbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSalvarActionPerformed
        // TODO add your handling code here:
        umaDisciplina.setCodigo(jTxtCodigo.getText());
        umaDisciplina.setNome(jTxtNome.getText());
        umaDisciplina.setCargaHoraria(jTxtCargaHoraria.getText());
        DisciplinaBLL.validaDados(umaDisciplina);
      
        if (Erro.getErro())
           JOptionPane.showMessageDialog(null,Erro.getMens());
        else{
           JOptionPane.showMessageDialog(null,"Dados Salvos com sucesso!");
           limpar();
        }
    }//GEN-LAST:event_JbtnSalvarActionPerformed
    //EVENTO BOTÃO CONSULTA
    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        // TODO add your handling code here:
         umaDisciplina.setCodigo(jTxtCodigo.getText());
        DisciplinaBLL.validaCodigo(umaDisciplina);
        if (Erro.getErro())
            JOptionPane.showMessageDialog(null,Erro.getMens());
        else
        {
            jTxtCodigo.setText(umaDisciplina.getCodigo());
            jTxtNome.setText(umaDisciplina.getNome());
            jTxtCargaHoraria.setText(umaDisciplina.getCargaHoraria());
            jBtnDeletar.setEnabled(true);
        jBtnAtualizar.setEnabled(true);
           
        }    
    }//GEN-LAST:event_jBtnConsultarActionPerformed
    //EVENTO BOTÃO LIMPAR
    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
        // TODO add your handling code here:
        limpar();
        jBtnDeletar.setEnabled(false);
        jBtnAtualizar.setEnabled(false);
        
    }//GEN-LAST:event_jBtnLimparActionPerformed

    private void jBtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeletarActionPerformed
        // TODO add your handling code here:
        umaDisciplina.setCodigo(jTxtCodigo.getText());
        
        DisciplinaBLL.deleteDisciplina(umaDisciplina);
      
        if (Erro.getErro())
           JOptionPane.showMessageDialog(null,Erro.getMens());
        else
        {    
           JOptionPane.showMessageDialog(null,"Disciplina excluída!");
           limpar();
           jBtnDeletar.setEnabled(false);
        jBtnAtualizar.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnDeletarActionPerformed

    private void jBtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtualizarActionPerformed
        // TODO add your handling code here:
        umaDisciplina.setCodigo(jTxtCodigo.getText());
        umaDisciplina.setNome(jTxtNome.getText());
        umaDisciplina.setCargaHoraria(jTxtCargaHoraria.getText());
        DisciplinaBLL.updateDisciplina(umaDisciplina);
      
        if (Erro.getErro())
           JOptionPane.showMessageDialog(null,Erro.getMens());
        else{
           JOptionPane.showMessageDialog(null,"Dados atualizados com sucesso!");
           limpar();
           jBtnDeletar.setEnabled(false);
        jBtnAtualizar.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisciplinaIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisciplinaIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisciplinaIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisciplinaIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisciplinaIHM().setVisible(true);
            }
        });
        
    }
    private Disciplina umaDisciplina = new Disciplina();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnSalvar;
    private javax.swing.JButton jBtnAtualizar;
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnDeletar;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTxtCargaHoraria;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
